;             
CREATE USER IF NOT EXISTS "" SALT '' HASH '' ADMIN;           
CREATE CACHED TABLE PUBLIC.STAKEHOLDERS(
    ID CHAR(8) NOT NULL,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    ROLE VARCHAR(255)
);        
ALTER TABLE PUBLIC.STAKEHOLDERS ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STAKEHOLDERS;            
CREATE CACHED TABLE PUBLIC.APPLICATIONS(
    APPID INT NOT NULL,
    PI CHAR(8) NOT NULL,
    ESO CHAR(8) NOT NULL,
    CONTACTPERSON CHAR(8) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    VERDICT VARCHAR(255) NOT NULL
);           
ALTER TABLE PUBLIC.APPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(APPID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.APPLICATIONS;            
CREATE CACHED TABLE PUBLIC.PENDINGAPPLICATIONS(
    APPID INT NOT NULL,
    HOS CHAR(8) NOT NULL,
    STATUS VARCHAR(255) NOT NULL
);     
ALTER TABLE PUBLIC.PENDINGAPPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(APPID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PENDINGAPPLICATIONS;     
CREATE CACHED TABLE PUBLIC.LOWRISKAPPLICATIONS(
    APPID INT NOT NULL,
    REVIEWER CHAR(8) NOT NULL,
    STATUS VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.LOWRISKAPPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_DE PRIMARY KEY(APPID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LOWRISKAPPLICATIONS;     
CREATE CACHED TABLE PUBLIC.HIGHRISKAPPLICATIONS(
    APPID INT NOT NULL,
    ETHICSOFFICER CHAR(8) NOT NULL,
    STATUS VARCHAR(255) NOT NULL
);          
ALTER TABLE PUBLIC.HIGHRISKAPPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(APPID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HIGHRISKAPPLICATIONS;    
ALTER TABLE PUBLIC.APPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_C1 FOREIGN KEY(PI) REFERENCES PUBLIC.STAKEHOLDERS(ID) NOCHECK;               
ALTER TABLE PUBLIC.HIGHRISKAPPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_BC FOREIGN KEY(ETHICSOFFICER) REFERENCES PUBLIC.STAKEHOLDERS(ID) NOCHECK;            
ALTER TABLE PUBLIC.APPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_C1FB FOREIGN KEY(CONTACTPERSON) REFERENCES PUBLIC.STAKEHOLDERS(ID) NOCHECK;  
ALTER TABLE PUBLIC.APPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_C1F FOREIGN KEY(ESO) REFERENCES PUBLIC.STAKEHOLDERS(ID) NOCHECK;             
ALTER TABLE PUBLIC.LOWRISKAPPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_DEE FOREIGN KEY(REVIEWER) REFERENCES PUBLIC.STAKEHOLDERS(ID) NOCHECK; 
ALTER TABLE PUBLIC.PENDINGAPPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_D7 FOREIGN KEY(APPID) REFERENCES PUBLIC.APPLICATIONS(APPID) NOCHECK;  
ALTER TABLE PUBLIC.PENDINGAPPLICATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_D78 FOREIGN KEY(HOS) REFERENCES PUBLIC.STAKEHOLDERS(ID) NOCHECK;      
