package views.formdata.application;

public enum AttachmentType {
    PROTOCOL_RESEARCH_PROPOSAL,
    RECRUITMENT_MATERIAL,
    PARTICIPANT_INFORMATION_STATEMENT_AND_CONSENT_FORMS,
    PARENT_INFORMATION_STATEMENT_AND_CONSENT_FORMS,
    CHILD_INFORMATION_STATEMENT_AND_ASSENT_FORMS,
    QUESTIONAIRES_SURVEY_INSTRUMENTS,
    TRANSLATIONS_WHERE_LANGUAGES_OTHER_THAN_ENGLISH_ARE_USED,
    RECRUITMENT_MATERIALS,
    INVESTIGATOR_BROCHURE_OR_PRODUCT_INFORMATION,
    WORKING_WITH_CHILDRENS_CARD,
    SOL;
}
